# Generated by Django 3.2.6 on 2021-08-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210814_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pub_link',
            field=models.CharField(default='None', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='affiliation_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('pub_link',)},
        ),
        migrations.RemoveField(
            model_name='report',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='publication_link',
        ),
    ]
