# Generated by Django 3.2.6 on 2021-08-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210814_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='embed_code',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
