# Generated by Django 3.2.6 on 2021-08-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_keyvaluepair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_type', models.CharField(max_length=25)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(max_length=25)),
                ('alt_names', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='report_subtype',
            field=models.CharField(default='General', max_length=25),
        ),
        migrations.AddField(
            model_name='report',
            name='require_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='bad_feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Help Needed', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('profile_link',)},
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location'),
        ),
    ]
