# Generated by Django 3.2.6 on 2021-08-19 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210817_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyvaluepair',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=50)),
                ('pub_link', models.CharField(max_length=250)),
                ('pub_time', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.author')),
            ],
        ),
    ]
