# Generated by Django 3.2.6 on 2021-08-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210819_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacoverage',
            name='author',
        ),
        migrations.AddField(
            model_name='mediacoverage',
            name='authors',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
