# Generated by Django 3.2.6 on 2021-08-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210820_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=100)),
                ('goal', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pub_link', models.CharField(max_length=250)),
                ('embed_code', models.CharField(max_length=1500)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.institution')),
                ('target_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Relief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('item_subtype', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('pub_link', models.CharField(max_length=250)),
                ('embed_code', models.CharField(max_length=1500)),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.institution')),
                ('target_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Aid',
        ),
    ]
