# Generated by Django 3.2.6 on 2021-08-22 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210821_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relief',
            old_name='institution',
            new_name='donor',
        ),
        migrations.AddField(
            model_name='relief',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_entries', to='app.institution'),
        ),
        migrations.AddField(
            model_name='relief',
            name='relief_designation',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fundraiser',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='relief',
            name='embed_code',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='relief',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.location'),
        ),
    ]
