# Generated by Django 3.2.6 on 2021-08-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210822_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='relief',
            name='donation_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relief',
            name='item_type',
            field=models.CharField(choices=[('Money', 'Money'), ('Food', 'Food'), ('Necessities', 'Necessities'), ('Personnel', 'Skilled Personnel'), ('Water', 'Water'), ('Construction Materials', 'Construction Materials'), ('Temporary Shelter', 'Temporary Shelter'), ('Medical care', 'Medical Care'), ('Medical Supplies', 'Medical Supplies'), ('Mental Care', 'Mental Care'), ('Other', 'Other')], max_length=50),
        ),
    ]
