# Generated by Django 3.2.6 on 2021-08-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210822_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relief',
            name='donation_date',
        ),
        migrations.AddField(
            model_name='relief',
            name='publication_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='relief',
            name='item_type',
            field=models.CharField(choices=[('Money', 'Capital'), ('Food', 'Food'), ('Necessities', 'Necessities'), ('Personnel', 'Skilled Personnel'), ('Water', 'Water'), ('Construction Materials', 'Construction Materials'), ('Temporary Shelter', 'Temporary Shelter'), ('Medical care', 'Medical Care'), ('Medical Supplies', 'Medical Supplies'), ('Mental Care', 'Mental Care'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='relief',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
