# Generated by Django 3.2.6 on 2021-08-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210824_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pub_link', models.CharField(max_length=250)),
                ('submission_datetime', models.DateTimeField(auto_now=True)),
                ('submission_type', models.CharField(max_length=15)),
            ],
            options={
                'unique_together': {('pub_link',)},
            },
        ),
    ]
