# Generated by Django 3.2.6 on 2021-08-25 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_usersubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='name',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='status',
            field=models.CharField(choices=[('Pending review', 'Pending Review'), ('Approved', 'Approved'), ('Dismissed', 'Dismissed')], default='Pending review', max_length=25),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='submission_type',
            field=models.CharField(choices=[('Relief', 'Relief'), ('Fundraiser', 'Fundraiser'), ('Report', 'Report')], max_length=15),
        ),
    ]
