# Generated by Django 3.2.6 on 2021-08-27 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210824_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='embed_code',
            field=models.CharField(max_length=15000),
        ),
    ]
