# Generated by Django 3.2.6 on 2021-08-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_report_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='publication_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
